apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-web-log-viewer-sa
  # namespace: your-target-namespace # Specify if not using kubectl -n flag 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-web-log-viewer-role
  # namespace: your-target-namespace # Should match the namespace of the ServiceAccount and Deployment
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"] # Allows access to pods and their logs
  verbs: ["get", "list", "watch"] # Allows reading/listing these resources 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-web-log-viewer-rb
  # namespace: your-target-namespace # Should match the Role and ServiceAccount namespace
subjects:
- kind: ServiceAccount
  name: kube-web-log-viewer-sa
  # namespace: your-target-namespace # Must be the namespace where the SA is defined
roleRef:
  kind: Role
  name: kube-web-log-viewer-role
  apiGroup: rbac.authorization.k8s.io 