apiVersion: v1
kind: Service
metadata:
  name: logpilot-service
  # namespace: your-target-namespace
  labels:
    app.kubernetes.io/name: logpilot
spec:
  selector:
    app.kubernetes.io/name: logpilot
  ports:
  - name: http
    protocol: TCP
    port: 5001
    targetPort: 5001