name: Delete Merged Branch (Non-Release)
on:
  pull_request:
    types:
      - closed
jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch is version branch
        id: check-version
        run: |
          BRANCH="${{ github.event.pull_request.head.ref }}"
          if [[ $BRANCH =~ ^v[0-9] ]]; then
            echo "is_version=true" >> $GITHUB_OUTPUT
          else
            echo "is_version=false" >> $GITHUB_OUTPUT
          fi
      - name: Delete non-release branch
        if: |
          !startsWith(github.event.pull_request.head.ref, 'release/') &&
          !startsWith(github.event.pull_request.head.ref, 'main') &&
          steps.check-version.outputs.is_version == 'false'
        run: |
          BRANCH=${{ github.event.pull_request.head.ref }}
          REPO=${{ github.repository }}
          echo "Deleting branch $BRANCH from $REPO"
          curl -s -X DELETE \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/git/refs/heads/$BRANCH
